### PR TITLE
Pr

### PR DESCRIPTION
**Pull request by tinoue70**
Committed 4 spreadsheet files for MIROC-ES2L, and modified model_publication.json.

### CODE REVIEW

**Comment by ghost** [comment]
@tinoue70 thx for this PR.  one of the ES-DOC team will review and get back to you if there are any issues - otherwise they will merge the PR.

**Review by sadielbartholomew — COMMENTED** [review]
Hi @tinoue70, thank you very much for submitting these. I've looked over them on behalf of the ES-DOC team and they generally look fine, but there are a small number of issues I have noticed, as outlined below. If you have any questions about my comments, please let me know and I will clarify.

### Breakdown by spreadsheet

#### Sea ice (`_seaice.xlsx`)

* 1.5.1.4 (Metrics Used) and 4.7.1.3 (Impacts) are compulsory properties to document, but they are both blank as-is. Please fill those items out, so that all the compulsory fields are completed.
* There are a few typos I noticed ("distibution" in 1.5.1.2 and "paramters" in 1.5.1.5)

#### Atmosphere (`_atmos.xlsx`)

* 2.1.2.2, 2.1.2.3, 3.2.1.2, 3.2.1.3, 3.4.3.3 - 3.4.3.5, 4.6.1.1, 4.12.1.1, 5.4.1.2 - 5.4.1.4, 7.3.1.3, 7.4.1.3, 9.3.1.2 - 9.3.1.5 are all compulsory but undocumented, again please fill these fields out.

#### Aerosol (`_aerosol.xlsx`)

* A '?' has been put for 1.1.1.5, please replace with a meaningful value for that field. If you are not sure what needs to be documented here, please let us know and we can provide further information.

#### Ocean (`_ocean.xlsx`)

(This one is fine as it is, thanks.)

**Comment by tinoue70** [comment]
Hi @sadielbartholomew, thank you very much for your review and comments.
I asked my colleagues to check and fix them.

BTW, **ocean**, **seaice** and **aerosol** are the same with (so copied from) MIROC6's version, so I'll fix and commit these for MIROC6 after this issue resolved.

**Comment by sadielbartholomew** [comment]
Perfect, thanks @tinoue70.

**Comment by tinoue70** [comment]
@sadielbartholomew I've just committed updates.

> ### Breakdown by spreadsheet
> #### Sea ice (`_seaice.xlsx`)
> 
> * 1.5.1.4 (Metrics Used) and 4.7.1.3 (Impacts) are compulsory properties to document, but they are both blank as-is. Please fill those items out, so that all the compulsory fields are completed.
> 
> * There are a few typos I noticed ("distibution" in 1.5.1.2 and "paramters" in 1.5.1.5)

Fixed.

> #### Atmosphere (`_atmos.xlsx`)
> 
> * 2.1.2.2, 2.1.2.3, 3.2.1.2, 3.2.1.3, 3.4.3.3 - 3.4.3.5, 4.6.1.1, 4.12.1.1, 5.4.1.2 - 5.4.1.4, 7.3.1.3, 7.4.1.3, 9.3.1.2 - 9.3.1.5 are all compulsory but undocumented, again please fill these fields out.

* 2.1.2.2, 2.1.2.3, 
Left 2.1.2.2 as blank. We can't find any appropriate choice because this model uses a spectral method.

* 3.2.1.2, 3.2.1.3, 3.4.3.3 - 3.4.3.5,
Fixed, but most of them are "N/A".

* 4.6.1.1, 4.12.1.1,
Fixed.

* 5.4.1.2 - 5.4.1.4,
Fixed, but all of them are "N/A" because this model does not consider shallow turbulence convection.

* 7.3.1.3, 7.4.1.3,
Left both as blank because this model uses a triangular function so there is no "function order".

* 9.3.1.2 - 9.3.1.5,
Left 9.3.1.3 as blank because this model does not treat non-orographic gravity waves.

> #### Aerosol (`_aerosol.xlsx`)
> 
>* A '?' has been put for 1.1.1.5, please replace with a meaningful value for that field. If you are not sure what needs to be documented here, please let us know and we can provide further information.

Fixed.

**Comment by tinoue70** [comment]
Just committed ocnbgchem for ES2L. Please check it too.

**Comment by sadielbartholomew** [comment]
Thank you for the updates @tinoue70 and sorry for the late reply, most of the ES-DOC core team including myself have been on leave over the past few weeks for our university winter closure days.

I'll review the new status of this PR and either merge it or provide further feedback later today, but from a glance it is all looking fine.

**Comment by sadielbartholomew** [comment]
I have now re-reviewed this Pull Request including the new ocean biogeochemistry realm spreadsheet and everything looks fine, so I will merge this.

Thanks again @tinoue70. Please note that as liaison for MIROC you will have push access to this repository, so unless you have specific questions regarding the spreadsheet(s) to be uploaded in each case, please go ahead and push commits directly to the repository instead of raising a PR; we have a validation process which will flag any invalid entries so if there are any issues they should be detected automatically, in which case we will get in touch to let you know they need amending. (If you have any questions about that process or pushing commits etc. please email our support email support@es-doc.org.)

**Comment by tinoue70** [comment]
Thank you @sadielbartholomew. Let me clarify two things.

- Now I can (should) commit to main branch, not PR, since the situation has changed from https://github.com/ES-DOC-INSTITUTIONAL/miroc/issues/1#issuecomment-673010372 that I was recommended to do so, right ?
- When will this commit appear on the explorer.es-doc.org ?

**Comment by sadielbartholomew** [comment]
Hi @tinoue70, please accept my apologies for the delay in responding. I think I missed your comment because I assumed the GitHub notification I got for this was simply to indicate it had been merged.

In response to your questions:

> Now I can (should) commit to main branch, not PR

Yes, please commit to the main branch from now on. (By the way, that was always an option, since in Mark's comment that you reference he said that you could do either a commit or a PR. Sorry if that wasn't clear.)

> When will this commit appear on the explorer.es-doc.org ?

We are in the middle of migrating the servers we use to host the ES-DOC site, so publication will not be on until that is completed. Therefore the data from this commit (and any others committed soon) won't appear on the explorer until the server migration is done.

We don't know exactly when that will be, but it will (probably) be by early February at the latest and may be a lot sooner. Sorry we can't say more specifically.

**Comment by tinoue70** [comment]
Hi @sadielbartholomew, thank you for your reply. OK, I understand. I'll wait for everything complete.

**Pull request merged**
